cache:
  - "c:\\sr -> stack.yaml"

install:
  - curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/windows-x86_64
  - 7z x stack.zip stack.exe

clone_folder: "c:\\project"

environment:
  global:
    STACK_ROOT: "c:\\sr"

test_script:
  - stack setup > nul
  - stack test --no-terminal --ghc-options -Wall

# before_deploy:
#   - ps: $BINARY = & stack path --local-install-root
#   - ps: $BINARY += "\\bin\\evaporate.exe"
#   -
#   - d
#   - 7z a -tzip README.md $BINARY
#
# deploy:
#   release: Evaporate
#   description: 'See CHANGELOG.md for changes'
#   provider: GitHub
#   auth_token:
#     secure: vQzw4N48UO9xekaqPdGR9mxKMlqUhT9cJGTkLWuS6ldXPBi+z4NEsN8csj4PJke2
#   artifact: zip file
#   draft: true
#   on:
#     branch: master
#     appveyor_repo_tag: true

build: off
